WORD_SIZE_BITS: int = 32
SIGN_BIT_INDEX: int = 0
MAGNITUDE_BITS: int = WORD_SIZE_BITS - 1

MAX_MAGNITUDE: int = (1 << MAGNITUDE_BITS) - 1

MIN_TWOS_COMPLEMENT: int = -(1 << MAGNITUDE_BITS)
MAX_TWOS_COMPLEMENT: int = (1 << MAGNITUDE_BITS) - 1